/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IERC721AMockInterface extends ethers.utils.Interface {
  functions: {
    "safeMint(address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "safeMint",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "safeMint", data: BytesLike): Result;

  events: {};
}

export class IERC721AMock extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IERC721AMockInterface;

  functions: {
    safeMint(
      to: string,
      quantity: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "safeMint(address,uint256)"(
      to: string,
      quantity: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  safeMint(
    to: string,
    quantity: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "safeMint(address,uint256)"(
    to: string,
    quantity: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    safeMint(
      to: string,
      quantity: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "safeMint(address,uint256)"(
      to: string,
      quantity: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    safeMint(
      to: string,
      quantity: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "safeMint(address,uint256)"(
      to: string,
      quantity: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    safeMint(
      to: string,
      quantity: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "safeMint(address,uint256)"(
      to: string,
      quantity: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
